# Generated by Django 5.0.3 on 2024-04-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='grau_de_dificuladade',
        ),
        migrations.AddField(
            model_name='receita',
            name='grau_de_dificuldade',
            field=models.CharField(blank=True, choices=[('Fácil', 'Fácil'), ('Moderado', 'Moderado'), ('Difícil', 'Difícil')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReceitaApp.categoria'),
        ),
    ]
